Fix the tests running with Pyramid 2.0
Without this change the tests fail with:

   `AttributeError: 'Request' object has no attribute 'registry'`

This introduces a factory function which will attach the local
registry to the request.